export const UI_STRINGS = {
  fr: {
    // Setup & login
    setupTitle: 'Configuration initiale',
    setupStep: (n) => `Étape ${n} sur 2 — Première utilisation`,
    setupInfo: 'Cette application fonctionne entièrement sur votre ordinateur. Aucun serveur ni internet requis.',
    institutionName: "Nom de l'établissement",
    institutionPlaceholder: 'ex: Institut Supérieur de Management',
    continue: 'Continuer',
    back: 'Retour',
    step2Intro: 'Créez votre compte administrateur. Vous pouvez tout gérer vous-même.',
    fullName: 'Nom complet',
    fullNamePlaceholder: 'ex: Dr. Kamga Paul',
    email: 'Email',
    emailPlaceholder: 'ex: directeur@ecole.edu',
    password: 'Mot de passe (min. 6 caractères)',
    confirmPassword: 'Confirmer le mot de passe',
    finishSetup: 'Terminer et ouvrir l\'application',
    configuring: 'Configuration...',
    addOtherLater: 'Ajouter un autre compte plus tard (optionnel)',
    addTimetablerHint: 'Vous pouvez ignorer ceci — l\'admin fait tout seul par défaut.',
    timetablerName: 'Nom du planificateur',
    timetablerEmail: 'Email planificateur',
    timetablerPassword: 'Mot de passe planificateur',
    errInstitution: "Entrez le nom de l'établissement.",
    errPasswordShort: 'Le mot de passe doit contenir au moins 6 caractères.',
    errPasswordMatch: 'Les mots de passe ne correspondent pas.',
    errRequired: 'Veuillez remplir tous les champs obligatoires.',
    errTimetabler: 'Remplissez les champs planificateur ou fermez cette section.',
    errSetup: 'Erreur lors de la configuration.',
    errLoginAfterSetup: 'Compte créé. Connectez-vous avec votre email et mot de passe.',
    loginTitle: 'Connexion sécurisée',
    loginSubtitle: 'Accès réservé au personnel autorisé.',
    loginLocal: 'Données stockées localement — aucun serveur requis',
    loginSubmit: 'Se connecter',
    loginAuthenticating: 'Connexion...',
    loginWrong: 'Email ou mot de passe incorrect',
    loginLocked: 'Session expirée après 30 min d\'inactivité. Reconnectez-vous.',

    // Navigation
    navPlanning: 'Planification',
    navData: 'Données',
    navDashboard: 'Tableau de bord',
    navTimetable: 'Emploi du Temps',
    navHistory: 'Historique',
    navMasterGrid: 'Grille Maîtresse',
    navConflicts: 'Conflits',
    navGroups: 'Groupes',
    navLecturers: 'Enseignants',
    navRooms: 'Salles',
    navCourses: 'Cours',
    navHolidays: 'Jours Fériés',
    navSettings: 'Paramètres',
    navLogout: 'Déconnexion',
    roleAdmin: 'Administrateur',
    roleTimetabler: 'Planificateur',
    roleUser: 'Utilisateur',
    localData: 'Données locales',
    search: 'Rechercher...',
    semesterBadge: 'Semestre 1 — 2025/2026',
    logoutTitle: 'Déconnexion',

    // Dashboard
    dashShareTitle: 'Comment partager aux étudiants',
    dashShareBody: 'Les étudiants ne consultent pas cette application. Générez l\'emploi du temps, exportez-le en PDF, puis envoyez le fichier dans vos groupes WhatsApp.',
    dashTitle: 'Tableau de bord',
    dashSubtitleReady: 'Tout est prêt — exportez et partagez sur WhatsApp.',
    dashSubtitleSteps: 'Suivez les étapes ci-dessous.',
    dashActive: 'Emploi du temps actif',
    dashReady: 'Prêt à planifier',
    dashChecklistTitle: 'Étapes pour la première semaine',
    dashStepSettings: 'Configurer l\'établissement (nom, semestre, logos)',
    dashStepData: 'Ajouter groupes, cours, enseignants et salles',
    dashStepGenerate: 'Générer l\'emploi du temps',
    dashStepExport: 'Exporter PDF et partager sur WhatsApp',
    dashNextStep: 'Prochaine étape :',
    dashStatGroups: 'Groupes',
    dashStatLecturers: 'Enseignants',
    dashStatRooms: 'Salles',
    dashStatCourses: 'Cours',
    dashStatSessions: 'Séances',
    dashStatConflicts: 'Conflits',
    dashGenTitle: 'Génération de l\'emploi du temps',
    dashGenSessions: (n) => `${n} séances`,
    dashGenNotYet: 'Pas encore généré',
    dashGenReady: 'Prêt à générer !',
    dashGenMissing: 'Données manquantes',
    dashGenReadyDetail: (g, l, c, r) => `${g} groupes · ${l} enseignants · ${c} cours · ${r} salles.`,
    dashGenMissingDetail: 'Ajoutez des cours, groupes, enseignants et salles avant de générer.',
    dashGenBtnView: 'Voir l\'emploi du temps',
    dashGenBtnGo: 'Générer maintenant',
    dashConflictsTitle: 'Conflits actifs',
    dashNoConflicts: 'Aucun conflit',
    dashNoConflictsOk: 'Emploi du temps cohérent.',
    dashNoConflictsFirst: 'Générez d\'abord l\'emploi du temps.',
    dashConflictsCount: (n) => `${n} conflit${n !== 1 ? 's' : ''}`,
    dashConflictsFix: 'Voir et corriger →',
    dashHowItWorksTitle: 'Comment ça marche',
    dashHowItWorks1: '1. Dans le menu gauche, section Données : ajoutez ou modifiez vos groupes, cours, enseignants et salles.',
    dashHowItWorks2: '2. Allez sur Emploi du Temps et cliquez Générer — l\'algorithme place automatiquement les séances.',
    dashHowItWorks3: '3. Exportez en PDF et partagez le fichier sur WhatsApp.',
    dashDemoNote: 'Des données de démonstration peuvent être préchargées. Remplacez-les par les vôtres dans le menu Données.',

    // Timetable
    ttTitle: 'Emploi du Temps',
    ttSubtitle: 'Générez l\'emploi du temps, exportez en PDF, puis partagez-le dans vos groupes WhatsApp.',
    ttGenerate: 'Générer l\'emploi du temps',
    ttGenerating: 'Génération...',
    ttExport: 'Exporter',
    ttExportPdf: 'PDF (format IUGET)',
    ttExportExcel: 'Exporter en Excel',
    ttPrint: 'Imprimer',
    ttClear: 'Effacer',
    ttShareHint: 'PDF téléchargé — ouvrez WhatsApp et envoyez-le à vos groupes étudiants.',
    ttPrereqTitle: 'Avant de générer',
    ttPrereqIntro: 'La génération automatique utilise vos données. Ajoutez-les d\'abord dans le menu Données (barre latérale gauche), puis revenez ici.',
    ttPrereqGroups: 'Groupes (classes / filières)',
    ttPrereqCourses: 'Cours (matières à planifier)',
    ttPrereqLecturers: 'Enseignants',
    ttPrereqRooms: 'Salles',
    ttPrereqManage: 'Gérer',
    ttPrereqReady: 'Tout est prêt — vous pouvez générer.',
    ttPrereqMissing: (items) => `Il manque : ${items}. Cliquez Gérer pour les ajouter.`,
    ttEmptyTitle: 'Aucun emploi du temps généré',
    ttEmptyBody: 'Une fois vos groupes, cours, enseignants et salles ajoutés, cliquez sur « Générer l\'emploi du temps ». L\'algorithme créera le planning automatiquement.',
    ttConfirmRegen: 'Cela effacera l\'emploi du temps actuel et toutes les modifications manuelles. Continuer ?',
    ttConfirmClear: 'Effacer tout l\'emploi du temps ?',
    ttErrNoData: 'Veuillez ajouter au moins un cours et un groupe avant de générer.',
    ttFilter: 'Filtrer:',
    ttAll: 'Tous',
    ttDay: 'Jour',
    ttEvening: 'Soir',
    ttPdfWhatsapp: 'PDF WhatsApp',
    ttSessions: (n) => `${n} séances`,
    ttNoConflicts: 'Sans conflits',
    ttDragHint: 'Glisser-déposer pour déplacer',
    ttGaConsole: 'Algorithme — Console',
    ttInstitution: 'Établissement',
    ttSecondary: 'Établissement Secondaire',
    ttUniversity: 'Établissement Universitaire',
    ttEveningClass: 'Cours du Soir',
    ttSchedule: 'Horaire',
    ttLock: 'Verrouiller',
    ttUnlock: 'Déverrouiller',
    ttGenerateDisabled: 'Ajoutez d\'abord groupes, cours, enseignants et salles',
    ttSavedToHistory: 'Enregistré dans Historique.',
    ttOpenHistory: 'Voir Historique →',
    ttArchiveView: 'Archive consultée',
    ttBackToLive: 'Retour à l\'actuel',
    ttScrollHint: 'Faites défiler horizontalement pour voir tous les jours',
    ttDays: 'jours',
    ttGroupsLegend: 'Chaque carte = un cours pour un groupe (ex. GL-3A, RT-SOIR). Plusieurs cartes dans une case = plusieurs groupes au même créneau.',
    ttSessionLabel: (n, total) => `Séance ${n}/${total}`,
    ttSessionWeek: (n, total) => `${n}e sur ${total} cette semaine`,
    ttGenHowTitle: 'Comment fonctionne la génération ?',
    ttGenHowBody: 'Le moteur lit vos Groupes, Cours, Enseignants et Salles (menu Données), puis place chaque séance dans un créneau libre pour la semaine choisie (Paramètres → numéro de semaine). Il évite les doubles réservations (même prof, même salle, même groupe). Régénérer remplace la semaine en cours — une seule copie est archivée dans Historique.',
    thTitle: 'Historique des emplois du temps',
    thSubtitle: 'Chaque génération est sauvegardée ici automatiquement avec la semaine et la date.',
    thEmpty: 'Aucun emploi du temps archivé',
    thEmptyHint: 'Générez un emploi du temps sur la page Emploi du Temps — il apparaîtra ici immédiatement.',
    thGenerated: 'Généré le',
    thSessions: 'séances',
    thBy: 'Par',
    thView: 'Consulter',
    thRestore: 'Rétablir',
    thConfirmRestore: 'Remplacer l\'emploi du temps actuel par cette version ?',
    thConfirmDelete: 'Supprimer cette archive ?',
    thNote: 'Les emplois du temps passés et actuels sont enregistrés dans la base locale du navigateur (IndexedDB « UniScheduleDB ») — ils restent après fermeture de l\'app. Les PDF exportés vont dans votre dossier Téléchargements. Rétablir remplace l\'emploi du temps en cours.',
    mgLegendTitle: 'Lecture de la grille',
    mgLegendBody: 'Sous chaque jour (Lundi, Mardi…), les petites colonnes sont vos groupes/classes : GL-3A, GL-3B, GL-SOIR, etc. — comme sur les emplois du temps IUGET / ENSPD / IAI.',
  },
  en: {
    setupTitle: 'Initial setup',
    setupStep: (n) => `Step ${n} of 2 — First time use`,
    setupInfo: 'This app runs entirely on your computer. No server or internet required.',
    institutionName: 'Institution name',
    institutionPlaceholder: 'e.g. Institute of Management',
    continue: 'Continue',
    back: 'Back',
    step2Intro: 'Create your administrator account. You can manage everything yourself.',
    fullName: 'Full name',
    fullNamePlaceholder: 'e.g. Dr. Kamga Paul',
    email: 'Email',
    emailPlaceholder: 'e.g. director@school.edu',
    password: 'Password (min. 6 characters)',
    confirmPassword: 'Confirm password',
    finishSetup: 'Finish and open the app',
    configuring: 'Setting up...',
    addOtherLater: 'Add another account later (optional)',
    addTimetablerHint: 'You can skip this — the admin can do everything alone.',
    timetablerName: 'Planner name',
    timetablerEmail: 'Planner email',
    timetablerPassword: 'Planner password',
    errInstitution: 'Enter the institution name.',
    errPasswordShort: 'Password must be at least 6 characters.',
    errPasswordMatch: 'Passwords do not match.',
    errRequired: 'Please fill in all required fields.',
    errTimetabler: 'Fill in planner fields or close this section.',
    errSetup: 'Setup error.',
    errLoginAfterSetup: 'Account created. Sign in with your email and password.',
    loginTitle: 'Secure sign in',
    loginSubtitle: 'Access for authorized staff only.',
    loginLocal: 'Data stored locally — no server required',
    loginSubmit: 'Sign in',
    loginAuthenticating: 'Signing in...',
    loginWrong: 'Incorrect email or password',
    loginLocked: 'Session expired after 30 min idle. Please sign in again.',

    navPlanning: 'Planning',
    navData: 'Data',
    navDashboard: 'Dashboard',
    navTimetable: 'Timetable',
    navHistory: 'History',
    navMasterGrid: 'Master Grid',
    navConflicts: 'Conflicts',
    navGroups: 'Groups',
    navLecturers: 'Lecturers',
    navRooms: 'Rooms',
    navCourses: 'Courses',
    navHolidays: 'Holidays',
    navSettings: 'Settings',
    navLogout: 'Sign out',
    roleAdmin: 'Administrator',
    roleTimetabler: 'Planner',
    roleUser: 'User',
    localData: 'Local data',
    search: 'Search...',
    semesterBadge: 'Semester 1 — 2025/2026',
    logoutTitle: 'Sign out',

    dashShareTitle: 'How to share with students',
    dashShareBody: 'Students do not use this app. Generate the timetable, export it as PDF, then send the file in your WhatsApp groups.',
    dashTitle: 'Dashboard',
    dashSubtitleReady: 'All set — export and share on WhatsApp.',
    dashSubtitleSteps: 'Follow the steps below.',
    dashActive: 'Timetable active',
    dashReady: 'Ready to plan',
    dashChecklistTitle: 'Steps for your first week',
    dashStepSettings: 'Configure institution (name, semester, logos)',
    dashStepData: 'Add groups, courses, lecturers and rooms',
    dashStepGenerate: 'Generate the timetable',
    dashStepExport: 'Export PDF and share on WhatsApp',
    dashNextStep: 'Next step:',
    dashStatGroups: 'Groups',
    dashStatLecturers: 'Lecturers',
    dashStatRooms: 'Rooms',
    dashStatCourses: 'Courses',
    dashStatSessions: 'Sessions',
    dashStatConflicts: 'Conflicts',
    dashGenTitle: 'Timetable generation',
    dashGenSessions: (n) => `${n} sessions`,
    dashGenNotYet: 'Not generated yet',
    dashGenReady: 'Ready to generate!',
    dashGenMissing: 'Missing data',
    dashGenReadyDetail: (g, l, c, r) => `${g} groups · ${l} lecturers · ${c} courses · ${r} rooms.`,
    dashGenMissingDetail: 'Add courses, groups, lecturers and rooms before generating.',
    dashGenBtnView: 'View timetable',
    dashGenBtnGo: 'Generate now',
    dashConflictsTitle: 'Active conflicts',
    dashNoConflicts: 'No conflicts',
    dashNoConflictsOk: 'Timetable is consistent.',
    dashNoConflictsFirst: 'Generate the timetable first.',
    dashConflictsCount: (n) => `${n} conflict${n !== 1 ? 's' : ''}`,
    dashConflictsFix: 'View and fix →',
    dashHowItWorksTitle: 'How it works',
    dashHowItWorks1: '1. In the left menu, Data section: add or edit your groups, courses, lecturers and rooms.',
    dashHowItWorks2: '2. Go to Timetable and click Generate — the algorithm places sessions automatically.',
    dashHowItWorks3: '3. Export as PDF and share the file on WhatsApp.',
    dashDemoNote: 'Demo data may be preloaded. Replace it with your own in the Data menu.',

    ttTitle: 'Timetable',
    ttSubtitle: 'Generate the timetable, export as PDF, then share it in your WhatsApp groups.',
    ttGenerate: 'Generate timetable',
    ttGenerating: 'Generating...',
    ttExport: 'Export',
    ttExportPdf: 'PDF (IUGET format)',
    ttExportExcel: 'Export to Excel',
    ttPrint: 'Print',
    ttClear: 'Clear',
    ttShareHint: 'PDF downloaded — open WhatsApp and send it to your student groups.',
    ttPrereqTitle: 'Before you generate',
    ttPrereqIntro: 'Automatic generation uses your data. Add it first in the Data menu (left sidebar), then come back here.',
    ttPrereqGroups: 'Groups (classes / programmes)',
    ttPrereqCourses: 'Courses (subjects to schedule)',
    ttPrereqLecturers: 'Lecturers',
    ttPrereqRooms: 'Rooms',
    ttPrereqManage: 'Manage',
    ttPrereqReady: 'All set — you can generate.',
    ttPrereqMissing: (items) => `Missing: ${items}. Click Manage to add them.`,
    ttEmptyTitle: 'No timetable generated yet',
    ttEmptyBody: 'Once you have added groups, courses, lecturers and rooms, click "Generate timetable". The algorithm will build the schedule automatically.',
    ttConfirmRegen: 'This will clear the current timetable and all manual edits. Continue?',
    ttConfirmClear: 'Clear the entire timetable?',
    ttErrNoData: 'Please add at least one course and one group before generating.',
    ttFilter: 'Filter:',
    ttAll: 'All',
    ttDay: 'Day',
    ttEvening: 'Evening',
    ttPdfWhatsapp: 'WhatsApp PDF',
    ttSessions: (n) => `${n} sessions`,
    ttNoConflicts: 'No conflicts',
    ttDragHint: 'Drag and drop to move',
    ttGaConsole: 'Algorithm — Console',
    ttInstitution: 'Institution',
    ttSecondary: 'Secondary School',
    ttUniversity: 'University',
    ttEveningClass: 'Evening class',
    ttSchedule: 'Time',
    ttLock: 'Lock',
    ttUnlock: 'Unlock',
    ttGenerateDisabled: 'Add groups, courses, lecturers and rooms first',
    ttSavedToHistory: 'Saved to History.',
    ttOpenHistory: 'Open History →',
    ttArchiveView: 'Viewing archive',
    ttBackToLive: 'Back to live',
    ttScrollHint: 'Scroll horizontally to see all days',
    ttDays: 'days',
    ttGroupsLegend: 'Each card = one course for one group (e.g. GL-3A, RT-EVENING). Multiple cards in a cell = several groups at the same time.',
    ttSessionLabel: (n, total) => `Session ${n}/${total}`,
    ttSessionWeek: (n, total) => `${n} of ${total} this week`,
    ttGenHowTitle: 'How does generation work?',
    ttGenHowBody: 'The engine reads your Groups, Courses, Lecturers and Rooms (Data menu), then places each session in a free slot for the selected week (Settings → week number). It avoids double bookings (same teacher, room, or group). Regenerate replaces the current week — only one copy is saved to History.',
    thTitle: 'Timetable history',
    thSubtitle: 'Each generation is saved here automatically with week and date.',
    thEmpty: 'No archived timetables',
    thEmptyHint: 'Generate a timetable on the Timetable page — it will appear here immediately.',
    thGenerated: 'Generated',
    thSessions: 'sessions',
    thBy: 'By',
    thView: 'View',
    thRestore: 'Restore',
    thConfirmRestore: 'Replace the current timetable with this version?',
    thConfirmDelete: 'Delete this archive?',
    thNote: 'Past and current timetables are saved in the browser\'s local database (IndexedDB « UniScheduleDB ») — they persist after you close the app. Exported PDFs go to your Downloads folder. Restore replaces the live timetable.',
    mgLegendTitle: 'How to read this grid',
    mgLegendBody: 'Under each day (Monday, Tuesday…), the small columns are your student groups: GL-3A, GL-3B, GL-EVENING, etc. — like IUGET / ENSPD / IAI timetables.',
  },
};

export function t(lang, key, ...args) {
  const pack = UI_STRINGS[lang] || UI_STRINGS.fr;
  const val = pack[key];
  if (typeof val === 'function') return val(...args);
  return val ?? key;
}
