export const UI_STRINGS = {
  fr: {
    // ── Common UI (shared across data pages) ──
    cAdd: 'Ajouter', cEdit: 'Modifier', cDelete: 'Supprimer', cCancel: 'Annuler',
    cSave: 'Enregistrer', cSaving: 'Enregistrement...', cActions: 'Actions',
    cLoading: 'Chargement...', cClose: 'Fermer', cRequired: 'requis',
    cName: 'Nom', cSpeciality: 'Filière', cLevel: 'Niveau', cSize: 'Effectif',
    cSlot: 'Créneau', cDay: 'Jour', cEvening: 'Soir', cType: 'Type',
    cCapacity: 'Capacité', cAvailability: 'Disponibilité', cDate: 'Date',
    cChooseSpeciality: '— Choisir une filière —', cCommonAllSpec: 'Cours commun (toutes filières)',
    cNoneFound: 'Aucun résultat.',

    // Groups page
    grpTitle: 'Groupes Étudiants', grpSubtitle: 'Gérez les classes, effectifs et filières.',
    grpAddBtn: 'Ajouter un groupe', grpSearchPh: 'Rechercher un groupe...',
    grpNone: 'Aucun groupe trouvé.', grpNew: 'Nouveau groupe', grpEdit: 'Modifier le groupe',
    grpNameLabel: 'Nom du groupe', grpNamePh: 'ex: GL-3A ou RT-SOIR',
    // Lecturers page
    lecTitle: 'Enseignants', lecSubtitle: 'Gérez le corps enseignant et les disponibilités.',
    lecAddBtn: 'Ajouter un enseignant', lecSearchPh: 'Rechercher un enseignant...',
    lecNone: 'Aucun enseignant trouvé.', lecNew: 'Nouvel enseignant', lecEdit: "Modifier l'enseignant",
    lecNameLabel: "Nom de l'enseignant", lecMaxHours: 'Heures max/sem.',
    lecPermanent: 'Permanent', lecVisiting: 'Visiteur', lecVacataire: 'Vacataire', lecPartTime: 'Temps partiel',
    lecStatus: 'Statut', lecMaxLoad: 'Charge max', lecAllSpec: 'Toutes filières',
    lecFullName: 'Nom complet', lecNamePh: 'ex: Dr. Tamo Jean', lecMainSpec: 'Filière principale',
    lecHoursWeek: 'h/sem',
    lecThisWeek: 'Cette semaine', lecAbsShort: 'abs.', lecViewDetail: 'voir détail',
    lecCoursesThisWeek: 'Cours cette semaine', lecAbsences: 'Absences (à rattraper)',
    lecNoAbsences: 'Aucune absence enregistrée.',
    lecSessionsN: (n) => `${n} séance${n > 1 ? 's' : ''}`,
    lecAbsN: (n) => `${n} absence${n > 1 ? 's' : ''}`,
    lecUnavailDays: 'Jours indisponibles', lecUnavailHint: "Le générateur ne placera aucun cours de cet enseignant ces jours-là.",
    wdMon: 'Lun', wdTue: 'Mar', wdWed: 'Mer', wdThu: 'Jeu', wdFri: 'Ven', wdSat: 'Sam', wdSun: 'Dim',
    // Rooms page
    rmTitle: 'Salles', rmSubtitle: 'Gérez les salles et leurs capacités.',
    rmAddBtn: 'Ajouter une salle', rmSearchPh: 'Rechercher une salle...',
    rmNone: 'Aucune salle trouvée.', rmNew: 'Nouvelle salle', rmEdit: 'Modifier la salle',
    rmNameLabel: 'Nom de la salle', rmEveAvail: 'Disponible le soir', rmDayOnly: 'Jour uniquement',
    rmAmphi: 'Amphithéâtre', rmClassroom: 'Salle de classe', rmLab: 'Laboratoire', rmSeminar: 'Séminaire',
    rmSeats: 'places', rmNamePh: 'ex: Amphi 500',
    // Courses page
    crsTitle: 'Catalogue des Cours', crsSubtitle: 'Définissez les modules, crédits et filières.',
    crsAddBtn: 'Ajouter un cours', crsSearchPh: 'Rechercher par code ou nom...',
    crsNone: 'Aucun cours trouvé.', crsNew: 'Nouveau cours', crsEdit: 'Modifier le cours',
    crsCode: 'Code', crsName: 'Intitulé', crsCredits: 'Crédits', crsHoursCol: 'H/sem', crsSessionsCol: 'Séances',
    crsCommon: 'Commun', crsPerSem: '/ sem.', crsAuto: '— auto',
    crsNameFr: 'Intitulé (Français)', crsNameEn: 'Intitulé (Anglais)',
    crsNameFrPh: 'Algorithmique et Structures de Données', crsNameEnPh: 'Algorithms & Data Structures',
    crsHoursWeek: 'Heures / semaine', crsHoursHint: '2h par créneau → séances/semaine calculées auto',
    crsSessionsSem: 'Séances au semestre', crsSessionsPh: 'ex. 30', crsSessionsHint: 'Vide = heures/sem × nb semaines',
    crsBlock: 'Cours en bloc (ex. labo 4h d\'affilée, 1 séance)',
    crsChoose: '— Choisir —', crsHoursUnit: 'h',
    // Holidays page
    holTitle: 'Jours Fériés & Congés', holSubtitle: "Ces dates apparaissent dans l'emploi du temps avec une bannière colorée.",
    holReseed: 'Fêtes Cameroun', holAddBtn: 'Ajouter un congé',
    holInfo: "Les jours fériés bloquent automatiquement les créneaux dans l'emploi du temps et apparaissent dans les exports PDF/Excel.",
    holNew: 'Nouveau Jour Férié', holNameFr: 'Nom (Français)', holNameEn: 'Nom (Anglais)',
    holNameFrPh: 'ex: Fête Nationale', holNameEnPh: 'ex: National Day',
    holNone: 'Aucun jour férié', holNoneHint: 'Cliquez sur « Fêtes Cameroun » pour charger les jours fériés officiels du Cameroun, ou ajoutez-en un manuellement.',
    holErrRequired: 'La date et le nom (FR) sont obligatoires.', holErrExists: 'Un congé existe déjà à cette date.',
    holDays: (n) => `${n} jour${n > 1 ? 's' : ''}`,
    holTypeNational: 'Fête Nationale', holTypeReligious: 'Fête Religieuse', holTypeAcademic: 'Académique', holTypeOther: 'Autre',
    // Settings page
    setTitle: 'Paramètres', setSubtitle: "Configuration de l'établissement · Apparaît sur tous les PDF exportés.",
    setLockedBanner: "En tant que Planificateur, vous pouvez modifier le semestre et les options d'affichage. Les logos, signatures et références officielles sont réservés à l'Administrateur.",
    setIdentity: "Identité de l'Établissement", setLogoMain: 'Logo Principal', setLogoSecond: 'Logo Secondaire',
    setInstName: "Nom de l'institution", setInstNamePh: 'ex: IUGET', setSchoolName: "Nom de l'école", setSchoolNamePh: 'ex: South Polytech',
    setInstType: "Type d'établissement",
    setTypeUni: 'Université / Grande École', setTypeUniDesc: '07h30–17h00 jour · 18h00–22h00 soir',
    setTypeSec: 'Lycée / Collège', setTypeSecDesc: '08h00–16h00 · pas de cours du soir',
    setHeaderTitle: "En-tête de l'Emploi du Temps", setHeaderInfo: 'Ces informations apparaissent dans le titre du PDF, comme sur les vrais emplois du temps.',
    setSemester: 'Semestre', setSemesterPh: 'ex: Sixth Semester', setCohort: 'Cohorte / Filière', setCohortPh: 'ex: B.TECH BONABERI',
    setCurrentWeek: 'Semaine actuelle', setCity: 'Ville', setCityPh: 'ex: Douala',
    setRefPrefix: 'Préfixe du numéro de référence', setRefPrefixPh: 'ex: IUGET/C-BHI/P-SP',
    setSignature: 'Bloc de Signature (bas de page PDF)', setSignerTitle: 'Titre du signataire', setSignerTitlePh: 'ex: Le Directeur',
    setSignerName: 'Nom du signataire', setSignerNamePh: 'ex: Claude A-ang',
    setOptions: "Options de l'Emploi du Temps", setIncludeSat: 'Inclure le Samedi',
    setSatDescSec: "Collèges / lycées : cours jusqu'au samedi", setSatDescUni: "Universités : colonne samedi dans l'emploi du temps",
    setIncludeSun: 'Inclure le Dimanche', setSunDesc: "Universités : cours jusqu'au dimanche (7 jours)",
    setDisplayLang: "Langue d'affichage",
    setUserMgmt: 'Gestion des Comptes', setUserMgmtHint: 'Seuls les comptes autorisés peuvent modifier les emplois du temps.',
    setAddAccount: 'Ajouter un compte', setFullNamePh: 'Nom complet', setEmailPh: 'Email', setPwPh: 'Mot de passe (min. 6)',
    setRoleAdmin: 'Administrateur', setRoleTimetabler: 'Planificateur', setCreateAccount: 'Créer le compte',
    setUserCreated: 'Compte créé avec succès.', setConfirmDeleteUser: 'Supprimer ce compte ?',
    setBackup: 'Sauvegarde des Données', setBackupHint: 'Exportez régulièrement vos données pour éviter toute perte.',
    setExportBackup: 'Exporter la sauvegarde', setImportBackup: 'Importer une sauvegarde',
    setBackupExported: 'Sauvegarde exportée.', setConfirmImport: 'Cette action remplacera toutes les données actuelles. Continuer ?',
    setRestored: 'Données restaurées. Rechargez la page.', setImportErr: "Erreur d'import.",
    setSpecRef: 'Filières Connues (Cameroun)', setSave: 'Sauvegarder', setSaved: 'Sauvegardé !',
    setAdminOnly: 'Admin uniquement', setLogoTooBig: 'Logo trop grand. Max: 500 Ko.',
    // Master Grid page
    mgTitle: 'Vue Ressources', mgExport: 'Exporter', mgExporting: 'Export...', mgPrint: 'Imprimer',
    mgPivotSpeciality: 'Par filière', mgPivotRoom: 'Par salle', mgPivotTeacher: 'Par enseignant',
    mgPivotHint: 'Vue d\'ensemble de l\'établissement. Choisissez ce que représentent les colonnes : filière, salle (occupation des salles) ou enseignant (emploi du temps de chaque prof).',
    mgNoData: 'Aucune donnée', mgNoDataHint: "Générez d'abord un emploi du temps dans l'onglet « Emploi du Temps ».",
    mgNoFilter: 'Aucun groupe ne correspond au filtre sélectionné.', mgEveningClass: 'Cours du Soir',
    mgPdfDownloaded: 'PDF téléchargé — ouvrez WhatsApp et envoyez-le à vos groupes étudiants.',
    mgSubtitle: (a, b) => `Vue combinée · ${a} filière${a !== 1 ? 's' : ''} · ${b} séances`,

    // Setup & login
    setupTitle: 'Configuration initiale',
    setupStep: (n) => `Étape ${n} sur 2 — Première utilisation`,
    setupInfo: 'Cette application fonctionne entièrement sur votre ordinateur. Aucun serveur ni internet requis.',
    institutionName: "Nom de l'établissement",
    institutionPlaceholder: 'ex: Institut Supérieur de Management',
    continue: 'Continuer',
    back: 'Retour',
    step2Intro: 'Créez votre compte administrateur. Vous pouvez tout gérer vous-même.',
    fullName: 'Nom complet',
    fullNamePlaceholder: 'ex: Dr. Kamga Paul',
    email: 'Email',
    emailPlaceholder: 'ex: directeur@ecole.edu',
    password: 'Mot de passe (min. 6 caractères)',
    confirmPassword: 'Confirmer le mot de passe',
    finishSetup: 'Terminer et ouvrir l\'application',
    configuring: 'Configuration...',
    addOtherLater: 'Ajouter un autre compte plus tard (optionnel)',
    addTimetablerHint: 'Vous pouvez ignorer ceci — l\'admin fait tout seul par défaut.',
    timetablerName: 'Nom du planificateur',
    timetablerEmail: 'Email planificateur',
    timetablerPassword: 'Mot de passe planificateur',
    errInstitution: "Entrez le nom de l'établissement.",
    errPasswordShort: 'Le mot de passe doit contenir au moins 6 caractères.',
    errPasswordMatch: 'Les mots de passe ne correspondent pas.',
    errRequired: 'Veuillez remplir tous les champs obligatoires.',
    errTimetabler: 'Remplissez les champs planificateur ou fermez cette section.',
    errSetup: 'Erreur lors de la configuration.',
    errLoginAfterSetup: 'Compte créé. Connectez-vous avec votre email et mot de passe.',
    loginTitle: 'Connexion sécurisée',
    loginSubtitle: 'Accès réservé au personnel autorisé.',
    loginLocal: 'Données stockées localement — aucun serveur requis',
    loginSubmit: 'Se connecter',
    loginAuthenticating: 'Connexion...',
    loginWrong: 'Email ou mot de passe incorrect',
    loginLocked: 'Session expirée après 30 min d\'inactivité. Reconnectez-vous.',
    loginHeroLine1: 'Nouvelle génération',
    loginHeroLine2: 'd\'emplois du temps intelligents',
    loginHeroDesc: 'Automatisez des contraintes de planification complexes, pensé pour l\'infrastructure éducative africaine.',
    loginFeat1Title: '100% Local',
    loginFeat1Desc: 'Fonctionne sur votre ordinateur, sans internet ni serveur.',
    loginFeat2Title: 'Export PDF → WhatsApp',
    loginFeat2Desc: 'Générez l\'emploi du temps, exportez en PDF, partagez aux étudiants.',
    loginFeat3Title: 'Natif double vacation',
    loginFeat3Desc: 'Conçu pour les créneaux Matin & Soir des établissements africains.',

    // Navigation
    navPlanning: 'Planification',
    navData: 'Données',
    navDashboard: 'Tableau de bord',
    navTimetable: 'Emploi du Temps',
    navHistory: 'Historique',
    navMasterGrid: 'Vue Ressources',
    navConflicts: 'Conflits',
    navGroups: 'Groupes',
    navLecturers: 'Enseignants',
    navRooms: 'Salles',
    navCourses: 'Cours',
    navHolidays: 'Jours Fériés',
    navSettings: 'Paramètres',
    navLogout: 'Déconnexion',
    roleAdmin: 'Administrateur',
    roleTimetabler: 'Planificateur',
    roleUser: 'Utilisateur',
    localData: 'Données locales',
    search: 'Rechercher...',
    semesterBadge: 'Semestre 1 — 2025/2026',
    logoutTitle: 'Déconnexion',

    // Dashboard
    dashShareTitle: 'Comment partager aux étudiants',
    dashShareBody: 'Les étudiants ne consultent pas cette application. Générez l\'emploi du temps, exportez-le en PDF, puis envoyez le fichier dans vos groupes WhatsApp.',
    dashTitle: 'Tableau de bord',
    dashSubtitleReady: 'Tout est prêt — exportez et partagez sur WhatsApp.',
    dashSubtitleSteps: 'Suivez les étapes ci-dessous.',
    dashActive: 'Emploi du temps actif',
    dashReady: 'Prêt à planifier',
    dashChecklistTitle: 'Étapes pour la première semaine',
    dashStepSettings: 'Configurer l\'établissement (nom, semestre, logos)',
    dashStepData: 'Ajouter groupes, cours, enseignants et salles',
    dashStepGenerate: 'Générer l\'emploi du temps',
    dashStepExport: 'Exporter PDF et partager sur WhatsApp',
    dashNextStep: 'Prochaine étape :',
    dashStatGroups: 'Groupes',
    dashStatLecturers: 'Enseignants',
    dashStatRooms: 'Salles',
    dashStatCourses: 'Cours',
    dashStatSessions: 'Séances',
    dashStatConflicts: 'Conflits',
    dashGenTitle: 'Génération de l\'emploi du temps',
    dashGenSessions: (n) => `${n} séances`,
    dashGenNotYet: 'Pas encore généré',
    dashGenReady: 'Prêt à générer !',
    dashGenMissing: 'Données manquantes',
    dashGenReadyDetail: (g, l, c, r) => `${g} groupes · ${l} enseignants · ${c} cours · ${r} salles.`,
    dashGenMissingDetail: 'Ajoutez des cours, groupes, enseignants et salles avant de générer.',
    dashGenBtnView: 'Voir l\'emploi du temps',
    dashGenBtnGo: 'Générer maintenant',
    dashConflictsTitle: 'Conflits actifs',
    dashAnalytics: 'Analyse de la semaine',
    dashSemesterProgress: 'Progression du semestre',
    dashWeekOf: (a, b) => `Semaine ${a} sur ${b}`,
    dashWeeklyHours: 'Heures de cours · semaine',
    dashAvgRoomUse: 'Occupation moyenne des salles',
    dashOverloaded: 'Enseignant(s) en surcharge',
    dashSubjectCoverage: 'Avancement par matière',
    dashSubjectCoverageHint: 'Séances planifiées jusqu\'à la semaine en cours / total du semestre',
    dashTeacherLoad: 'Charge des enseignants',
    dashTeacherLoadHint: 'Heures cette semaine / maximum hebdomadaire',
    dashRoomUse: 'Occupation des salles',
    dashRoomUseHint: 'Créneaux occupés cette semaine / créneaux disponibles',
    dashSessionsByDay: 'Séances par jour',
    dashQuality: "Qualité de l'emploi du temps", dashQualityScore: 'Score de qualité',
    qNoClash: 'Sans conflit', qCompact: 'Journées compactes', qSpread: 'Matières réparties',
    qLoad: 'Charge enseignants', qRoomType: 'Type de salle respecté', qAvail: 'Disponibilités respectées',
    dashFairness: 'Équité', dashBalance: 'Équilibre des charges', dashBusiest: 'Plus chargé', dashLightest: 'Moins chargé',
    dashWorstClass: 'Classe avec le plus de trous', dashGapsN: (n) => `${n} trou${n > 1 ? 's' : ''}`,
    dashWhatIf: 'Simulation « Et si… ? »', dashWhatIfHint: 'Testez un changement de ressources sans toucher à vos données réelles.',
    dashSimAddTeacher: '+1 enseignant', dashSimRemoveRoom: 'Retirer une salle', dashSimReset: 'Réinitialiser',
    dashSimRun: 'Simuler', dashSimRunning: 'Simulation...', dashSimCurrent: 'Actuel', dashSimProjected: 'Projeté',
    dashSimClashesN: (n) => `${n} conflit${n > 1 ? 's' : ''}`,
    dashNoData: 'Générez un emploi du temps pour voir les statistiques.',
    dashDone: 'fait',
    dashOver: 'dépassé',
    dashNoConflicts: 'Aucun conflit',
    dashNoConflictsOk: 'Emploi du temps cohérent.',
    dashNoConflictsFirst: 'Générez d\'abord l\'emploi du temps.',
    dashConflictsCount: (n) => `${n} conflit${n !== 1 ? 's' : ''}`,
    dashConflictsFix: 'Voir et corriger →',
    dashHowItWorksTitle: 'Comment ça marche',
    dashHowItWorks1: '1. Dans le menu gauche, section Données : ajoutez ou modifiez vos groupes, cours, enseignants et salles.',
    dashHowItWorks2: '2. Allez sur Emploi du Temps et cliquez Générer — l\'algorithme place automatiquement les séances.',
    dashHowItWorks3: '3. Exportez en PDF et partagez le fichier sur WhatsApp.',
    dashDemoNote: 'Des données de démonstration peuvent être préchargées. Remplacez-les par les vôtres dans le menu Données.',

    // Timetable
    ttTitle: 'Emploi du Temps',
    ttSubtitle: 'Générez l\'emploi du temps, exportez en PDF, puis partagez-le dans vos groupes WhatsApp.',
    ttGenerate: 'Générer l\'emploi du temps',
    ttGenerating: 'Génération...',
    ttExport: 'Exporter',
    ttExportPdf: 'PDF (format IUGET)',
    ttExportAllLevels: 'PDF — Tous les niveaux (1 page/classe)',
    ttExportPerLecturer: 'PDF — Par enseignant (1 page/prof)',
    diagTitle: 'Avant de générer — points de vigilance',
    diagGroupOverflow: (g, n, cap) => `${g} : ${n} séances demandées cette semaine, mais seulement ${cap} créneaux disponibles. Réduisez les cours ou ajoutez des créneaux.`,
    diagOversizedGroup: (g, size, max) => `${g} (${size} étudiants) : aucune salle assez grande (max ${max} places). Ajoutez une salle plus grande.`,
    diagRoomSupply: (mode, demand, supply) => `Créneaux ${mode} : ${demand} séances à placer mais seulement ${supply} salles×créneaux. Des conflits de salle sont probables — ajoutez une salle.`,
    diagLecOverload: (lec, load, cap) => `${lec} : ${load} séances lui sont imposées, mais seulement ${cap} créneaux disponibles. Ajoutez un enseignant pour ces cours.`,
    ttExportExcel: 'Exporter en Excel',
    ttPrint: 'Imprimer',
    ttClear: 'Effacer',
    ttShareHint: 'PDF téléchargé — ouvrez WhatsApp et envoyez-le à vos groupes étudiants.',
    ttPrereqTitle: 'Avant de générer',
    ttPrereqIntro: 'La génération automatique utilise vos données. Ajoutez-les d\'abord dans le menu Données (barre latérale gauche), puis revenez ici.',
    ttPrereqGroups: 'Groupes (classes / filières)',
    ttPrereqCourses: 'Cours (matières à planifier)',
    ttPrereqLecturers: 'Enseignants',
    ttPrereqRooms: 'Salles',
    ttPrereqManage: 'Gérer',
    ttPrereqReady: 'Tout est prêt — vous pouvez générer.',
    ttPrereqMissing: (items) => `Il manque : ${items}. Cliquez Gérer pour les ajouter.`,
    ttEmptyTitle: 'Aucun emploi du temps généré',
    ttEmptyBody: 'Une fois vos groupes, cours, enseignants et salles ajoutés, cliquez sur « Générer l\'emploi du temps ». L\'algorithme créera le planning automatiquement.',
    ttConfirmRegen: 'Cela effacera l\'emploi du temps actuel et toutes les modifications manuelles. Continuer ?',
    ttConfirmClear: 'Effacer tout l\'emploi du temps ?',
    ttErrNoData: 'Veuillez ajouter au moins un cours et un groupe avant de générer.',
    ttFilter: 'Filtrer:',
    ttAll: 'Tous',
    ttAllHint: 'Vue d\'ensemble — chaque carte est une classe différente',
    ttLevel: 'Niveau',
    ttClassTimetable: 'Emploi du temps de la classe',
    ttPickClass: 'Choisissez une classe ci-dessus pour voir son emploi du temps (une seule matière par créneau).',
    ttDay: 'Jour',
    ttEvening: 'Soir',
    ttPdfWhatsapp: 'PDF WhatsApp',
    ttSessions: (n) => `${n} séances`,
    ttNoConflicts: 'Sans conflits',
    ttDragHint: 'Glisser-déposer pour déplacer',
    ttGaConsole: 'Algorithme — Console',
    ttInstitution: 'Établissement',
    ttSecondary: 'Établissement Secondaire',
    ttUniversity: 'Établissement Universitaire',
    ttEveningClass: 'Cours du Soir',
    ttSchedule: 'Horaire',
    ttLock: 'Verrouiller',
    ttUnlock: 'Déverrouiller',
    ttDeleteSession: 'Supprimer cette séance',
    ttCopySession: 'Dupliquer cette séance',
    ttAddSession: 'Ajouter une séance', ttAddGroup: 'Groupe', ttAddCourse: 'Cours', ttAddTeacher: 'Enseignant',
    ttAddRoom: 'Salle', ttAddDay: 'Jour', ttAddSlot: 'Créneau', ttAddPick: '— Choisir —',
    ttConfirmDeleteSession: (label) => `Supprimer la séance « ${label} » de cette semaine ?`,
    ttMarkMissed: 'Marquer comme manquée',
    ttMissedWithMakeup: 'Manquée — à rattraper',
    ttMissedNoMakeup: 'Manquée — sans rattrapage',
    ttUnmarkMissed: 'Annuler l\'absence',
    ttMissedBadge: 'Manquée',
    ttMakeupBadge: 'Rattrapage',
    ttBlock: 'bloc',
    ttGenerateDisabled: 'Ajoutez d\'abord groupes, cours, enseignants et salles',
    ttSavedToHistory: 'Enregistré dans Historique.',
    ttOpenHistory: 'Voir Historique →',
    ttArchiveView: 'Archive consultée',
    ttBackToLive: 'Retour à l\'actuel',
    ttScrollHint: 'Faites défiler horizontalement pour voir tous les jours',
    ttDays: 'jours',
    ttGroupsLegend: 'Chaque carte = un cours pour un groupe (ex. GL-3A, RT-SOIR). Plusieurs cartes dans une case = plusieurs groupes au même créneau.',
    ttSessionLabel: (n, total) => `Séance ${n}/${total}`,
    ttSessionWeek: (n, total) => `${n}e sur ${total} cette semaine`,
    ttGenHowTitle: 'Comment fonctionne la génération ?',
    ttGenHowBody: 'Le moteur lit vos Groupes, Cours, Enseignants et Salles (menu Données), puis place chaque séance dans un créneau libre pour la semaine choisie (Paramètres → numéro de semaine). Il évite les doubles réservations (même prof, même salle, même groupe). Régénérer remplace la semaine en cours — une seule copie est archivée dans Historique.',
    thTitle: 'Historique des emplois du temps',
    thSubtitle: 'Chaque génération est sauvegardée ici automatiquement avec la semaine et la date.',
    thEmpty: 'Aucun emploi du temps archivé',
    thEmptyHint: 'Générez un emploi du temps sur la page Emploi du Temps — il apparaîtra ici immédiatement.',
    thGenerated: 'Généré le',
    thSessions: 'séances',
    thBy: 'Par',
    thView: 'Consulter',
    thRestore: 'Rétablir',
    thConfirmRestore: 'Remplacer l\'emploi du temps actuel par cette version ?',
    thConfirmDelete: 'Supprimer cette archive ?',
    thNote: 'Les emplois du temps passés et actuels sont enregistrés dans la base locale du navigateur (IndexedDB « UniScheduleDB ») — ils restent après fermeture de l\'app. Les PDF exportés vont dans votre dossier Téléchargements. Rétablir remplace l\'emploi du temps en cours.',
    mgLegendTitle: 'Lecture de la grille',
    mgLegendBody: 'Sous chaque jour (Lundi, Mardi…), les petites colonnes sont vos groupes/classes : GL-3A, GL-3B, GL-SOIR, etc. — comme sur les emplois du temps IUGET / ENSPD / IAI.',
  },
  en: {
    // ── Common UI (shared across data pages) ──
    cAdd: 'Add', cEdit: 'Edit', cDelete: 'Delete', cCancel: 'Cancel',
    cSave: 'Save', cSaving: 'Saving...', cActions: 'Actions',
    cLoading: 'Loading...', cClose: 'Close', cRequired: 'required',
    cName: 'Name', cSpeciality: 'Speciality', cLevel: 'Level', cSize: 'Size',
    cSlot: 'Slot', cDay: 'Day', cEvening: 'Evening', cType: 'Type',
    cCapacity: 'Capacity', cAvailability: 'Availability', cDate: 'Date',
    cChooseSpeciality: '— Choose a speciality —', cCommonAllSpec: 'Common course (all specialities)',
    cNoneFound: 'No results.',

    // Groups page
    grpTitle: 'Student Groups', grpSubtitle: 'Manage classes, sizes and specialities.',
    grpAddBtn: 'Add a group', grpSearchPh: 'Search a group...',
    grpNone: 'No groups found.', grpNew: 'New group', grpEdit: 'Edit group',
    grpNameLabel: 'Group name', grpNamePh: 'e.g. GL-3A or RT-EVENING',
    // Lecturers page
    lecTitle: 'Lecturers', lecSubtitle: 'Manage teaching staff and availability.',
    lecAddBtn: 'Add a lecturer', lecSearchPh: 'Search a lecturer...',
    lecNone: 'No lecturers found.', lecNew: 'New lecturer', lecEdit: 'Edit lecturer',
    lecNameLabel: 'Lecturer name', lecMaxHours: 'Max hours/week',
    lecPermanent: 'Permanent', lecVisiting: 'Visiting', lecVacataire: 'Contract', lecPartTime: 'Part-time',
    lecStatus: 'Status', lecMaxLoad: 'Max load', lecAllSpec: 'All specialities',
    lecFullName: 'Full name', lecNamePh: 'e.g. Dr. Tamo Jean', lecMainSpec: 'Main speciality',
    lecHoursWeek: 'h/wk',
    lecThisWeek: 'This week', lecAbsShort: 'abs.', lecViewDetail: 'view detail',
    lecCoursesThisWeek: 'Courses this week', lecAbsences: 'Absences (to make up)',
    lecNoAbsences: 'No absences recorded.',
    lecSessionsN: (n) => `${n} session${n > 1 ? 's' : ''}`,
    lecAbsN: (n) => `${n} absence${n > 1 ? 's' : ''}`,
    lecUnavailDays: 'Unavailable days', lecUnavailHint: "The generator won't place any of this teacher's classes on these days.",
    wdMon: 'Mon', wdTue: 'Tue', wdWed: 'Wed', wdThu: 'Thu', wdFri: 'Fri', wdSat: 'Sat', wdSun: 'Sun',
    // Rooms page
    rmTitle: 'Rooms', rmSubtitle: 'Manage rooms and their capacities.',
    rmAddBtn: 'Add a room', rmSearchPh: 'Search a room...',
    rmNone: 'No rooms found.', rmNew: 'New room', rmEdit: 'Edit room',
    rmNameLabel: 'Room name', rmEveAvail: 'Available in the evening', rmDayOnly: 'Day only',
    rmAmphi: 'Lecture hall', rmClassroom: 'Classroom', rmLab: 'Laboratory', rmSeminar: 'Seminar',
    rmSeats: 'seats', rmNamePh: 'e.g. Hall 500',
    // Courses page
    crsTitle: 'Course Catalogue', crsSubtitle: 'Define modules, credits and specialities.',
    crsAddBtn: 'Add a course', crsSearchPh: 'Search by code or name...',
    crsNone: 'No courses found.', crsNew: 'New course', crsEdit: 'Edit course',
    crsCode: 'Code', crsName: 'Title', crsCredits: 'Credits', crsHoursCol: 'H/wk', crsSessionsCol: 'Sessions',
    crsCommon: 'Common', crsPerSem: '/ sem.', crsAuto: '— auto',
    crsNameFr: 'Title (French)', crsNameEn: 'Title (English)',
    crsNameFrPh: 'Algorithmique et Structures de Données', crsNameEnPh: 'Algorithms & Data Structures',
    crsHoursWeek: 'Hours / week', crsHoursHint: '2h per slot → sessions/week auto-calculated',
    crsSessionsSem: 'Sessions per semester', crsSessionsPh: 'e.g. 30', crsSessionsHint: 'Empty = hours/week × number of weeks',
    crsBlock: 'Block course (e.g. 4h lab in one sitting, 1 session)',
    crsRoomType: 'Required room type', crsAnyRoom: 'Any room',
    crsChoose: '— Choose —', crsHoursUnit: 'h',
    // Holidays page
    holTitle: 'Public Holidays & Breaks', holSubtitle: 'These dates appear in the timetable with a colored banner.',
    holReseed: 'Cameroon holidays', holAddBtn: 'Add a holiday',
    holInfo: 'Holidays automatically block timetable slots and appear in PDF/Excel exports.',
    holNew: 'New holiday', holNameFr: 'Name (French)', holNameEn: 'Name (English)',
    holNameFrPh: 'e.g. National Day', holNameEnPh: 'e.g. National Day',
    holNone: 'No holidays', holNoneHint: 'Click "Cameroon holidays" to load Cameroon\'s official public holidays, or add one manually.',
    holErrRequired: 'Date and name (FR) are required.', holErrExists: 'A holiday already exists on this date.',
    holDays: (n) => `${n} day${n > 1 ? 's' : ''}`,
    holTypeNational: 'National holiday', holTypeReligious: 'Religious holiday', holTypeAcademic: 'Academic', holTypeOther: 'Other',
    // Settings page
    setTitle: 'Settings', setSubtitle: 'Institution configuration · Appears on all exported PDFs.',
    setLockedBanner: 'As a Scheduler, you can change the semester and display options. Logos, signatures and official references are reserved for the Administrator.',
    setIdentity: 'Institution Identity', setLogoMain: 'Main Logo', setLogoSecond: 'Secondary Logo',
    setInstName: 'Institution name', setInstNamePh: 'e.g. IUGET', setSchoolName: 'School name', setSchoolNamePh: 'e.g. South Polytech',
    setInstType: 'Institution type',
    setTypeUni: 'University / College', setTypeUniDesc: '07:30–17:00 day · 18:00–22:00 evening',
    setTypeSec: 'Secondary School', setTypeSecDesc: '08:00–16:00 · no evening classes',
    setHeaderTitle: 'Timetable Header', setHeaderInfo: 'This information appears in the PDF title, like on real timetables.',
    setSemester: 'Semester', setSemesterPh: 'e.g. Sixth Semester', setCohort: 'Cohort / Programme', setCohortPh: 'e.g. B.TECH BONABERI',
    setCurrentWeek: 'Current week', setCity: 'City', setCityPh: 'e.g. Douala',
    setRefPrefix: 'Reference number prefix', setRefPrefixPh: 'e.g. IUGET/C-BHI/P-SP',
    setSignature: 'Signature Block (PDF footer)', setSignerTitle: 'Signer title', setSignerTitlePh: 'e.g. The Director',
    setSignerName: 'Signer name', setSignerNamePh: 'e.g. Claude A-ang',
    setOptions: 'Timetable Options', setIncludeSat: 'Include Saturday',
    setSatDescSec: 'Secondary schools: classes through Saturday', setSatDescUni: 'Universities: Saturday column in the timetable',
    setIncludeSun: 'Include Sunday', setSunDesc: 'Universities: classes through Sunday (7 days)',
    setDisplayLang: 'Display language',
    setUserMgmt: 'Account Management', setUserMgmtHint: 'Only authorized accounts can edit timetables.',
    setAddAccount: 'Add an account', setFullNamePh: 'Full name', setEmailPh: 'Email', setPwPh: 'Password (min. 6)',
    setRoleAdmin: 'Administrator', setRoleTimetabler: 'Scheduler', setCreateAccount: 'Create account',
    setUserCreated: 'Account created successfully.', setConfirmDeleteUser: 'Delete this account?',
    setBackup: 'Data Backup', setBackupHint: 'Export your data regularly to avoid any loss.',
    setExportBackup: 'Export backup', setImportBackup: 'Import backup',
    setBackupExported: 'Backup exported.', setConfirmImport: 'This will replace all current data. Continue?',
    setRestored: 'Data restored. Reload the page.', setImportErr: 'Import error.',
    setSpecRef: 'Known Specialities (Cameroon)', setSave: 'Save', setSaved: 'Saved!',
    setAdminOnly: 'Admin only', setLogoTooBig: 'Logo too large. Max: 500 KB.',
    // Master Grid page
    mgTitle: 'Resource View', mgExport: 'Export', mgExporting: 'Exporting...', mgPrint: 'Print',
    mgPivotSpeciality: 'By speciality', mgPivotRoom: 'By room', mgPivotTeacher: 'By teacher',
    mgPivotHint: 'Institution-wide overview. Choose what the columns represent: speciality, room (room occupancy), or teacher (each teacher\'s week).',
    mgNoData: 'No data', mgNoDataHint: 'First generate a timetable in the "Timetable" tab.',
    mgNoFilter: 'No group matches the selected filter.', mgEveningClass: 'Evening class',
    mgPdfDownloaded: 'PDF downloaded — open WhatsApp and send it to your student groups.',
    mgSubtitle: (a, b) => `Combined view · ${a} ${a === 1 ? 'speciality' : 'specialities'} · ${b} sessions`,

    setupTitle: 'Initial setup',
    setupStep: (n) => `Step ${n} of 2 — First time use`,
    setupInfo: 'This app runs entirely on your computer. No server or internet required.',
    institutionName: 'Institution name',
    institutionPlaceholder: 'e.g. Institute of Management',
    continue: 'Continue',
    back: 'Back',
    step2Intro: 'Create your administrator account. You can manage everything yourself.',
    fullName: 'Full name',
    fullNamePlaceholder: 'e.g. Dr. Kamga Paul',
    email: 'Email',
    emailPlaceholder: 'e.g. director@school.edu',
    password: 'Password (min. 6 characters)',
    confirmPassword: 'Confirm password',
    finishSetup: 'Finish and open the app',
    configuring: 'Setting up...',
    addOtherLater: 'Add another account later (optional)',
    addTimetablerHint: 'You can skip this — the admin can do everything alone.',
    timetablerName: 'Planner name',
    timetablerEmail: 'Planner email',
    timetablerPassword: 'Planner password',
    errInstitution: 'Enter the institution name.',
    errPasswordShort: 'Password must be at least 6 characters.',
    errPasswordMatch: 'Passwords do not match.',
    errRequired: 'Please fill in all required fields.',
    errTimetabler: 'Fill in planner fields or close this section.',
    errSetup: 'Setup error.',
    errLoginAfterSetup: 'Account created. Sign in with your email and password.',
    loginTitle: 'Secure sign in',
    loginSubtitle: 'Access for authorized staff only.',
    loginLocal: 'Data stored locally — no server required',
    loginSubmit: 'Sign in',
    loginHeroLine1: 'Next-Gen',
    loginHeroLine2: 'Timetable Intelligence',
    loginHeroDesc: 'Automate complex scheduling constraints, natively designed for African educational infrastructure.',
    loginFeat1Title: '100% Local',
    loginFeat1Desc: 'Runs on your computer — no internet, no server.',
    loginFeat2Title: 'Export PDF → WhatsApp',
    loginFeat2Desc: 'Generate the timetable, export to PDF, share with students.',
    loginFeat3Title: 'Double-Shift Native',
    loginFeat3Desc: 'Built for the morning & evening slots of African institutions.',
    loginAuthenticating: 'Signing in...',
    loginWrong: 'Incorrect email or password',
    loginLocked: 'Session expired after 30 min idle. Please sign in again.',

    navPlanning: 'Planning',
    navData: 'Data',
    navDashboard: 'Dashboard',
    navTimetable: 'Timetable',
    navHistory: 'History',
    navMasterGrid: 'Resource View',
    navConflicts: 'Conflicts',
    navGroups: 'Groups',
    navLecturers: 'Lecturers',
    navRooms: 'Rooms',
    navCourses: 'Courses',
    navHolidays: 'Holidays',
    navSettings: 'Settings',
    navLogout: 'Sign out',
    roleAdmin: 'Administrator',
    roleTimetabler: 'Planner',
    roleUser: 'User',
    localData: 'Local data',
    search: 'Search...',
    semesterBadge: 'Semester 1 — 2025/2026',
    logoutTitle: 'Sign out',

    dashShareTitle: 'How to share with students',
    dashShareBody: 'Students do not use this app. Generate the timetable, export it as PDF, then send the file in your WhatsApp groups.',
    dashTitle: 'Dashboard',
    dashSubtitleReady: 'All set — export and share on WhatsApp.',
    dashSubtitleSteps: 'Follow the steps below.',
    dashActive: 'Timetable active',
    dashReady: 'Ready to plan',
    dashChecklistTitle: 'Steps for your first week',
    dashStepSettings: 'Configure institution (name, semester, logos)',
    dashStepData: 'Add groups, courses, lecturers and rooms',
    dashStepGenerate: 'Generate the timetable',
    dashStepExport: 'Export PDF and share on WhatsApp',
    dashNextStep: 'Next step:',
    dashStatGroups: 'Groups',
    dashStatLecturers: 'Lecturers',
    dashStatRooms: 'Rooms',
    dashStatCourses: 'Courses',
    dashStatSessions: 'Sessions',
    dashStatConflicts: 'Conflicts',
    dashGenTitle: 'Timetable generation',
    dashGenSessions: (n) => `${n} sessions`,
    dashGenNotYet: 'Not generated yet',
    dashGenReady: 'Ready to generate!',
    dashGenMissing: 'Missing data',
    dashGenReadyDetail: (g, l, c, r) => `${g} groups · ${l} lecturers · ${c} courses · ${r} rooms.`,
    dashGenMissingDetail: 'Add courses, groups, lecturers and rooms before generating.',
    dashGenBtnView: 'View timetable',
    dashGenBtnGo: 'Generate now',
    dashConflictsTitle: 'Active conflicts',
    dashAnalytics: 'This week at a glance',
    dashSemesterProgress: 'Semester progress',
    dashWeekOf: (a, b) => `Week ${a} of ${b}`,
    dashWeeklyHours: 'Teaching hours · week',
    dashAvgRoomUse: 'Average room occupancy',
    dashOverloaded: 'Overloaded teacher(s)',
    dashSubjectCoverage: 'Coverage by subject',
    dashSubjectCoverageHint: 'Sessions scheduled up to the current week / semester total',
    dashTeacherLoad: 'Teacher workload',
    dashTeacherLoadHint: 'Hours this week / weekly maximum',
    dashRoomUse: 'Room utilization',
    dashRoomUseHint: 'Slots used this week / available slots',
    dashSessionsByDay: 'Sessions per day',
    dashQuality: 'Timetable quality', dashQualityScore: 'Quality score',
    qNoClash: 'Clash-free', qCompact: 'Compact days', qSpread: 'Subjects spread out',
    qLoad: 'Teacher load', qRoomType: 'Room-type respected', qAvail: 'Availability respected',
    dashFairness: 'Fairness', dashBalance: 'Workload balance', dashBusiest: 'Busiest', dashLightest: 'Lightest',
    dashWorstClass: 'Class with most gaps', dashGapsN: (n) => `${n} gap${n > 1 ? 's' : ''}`,
    dashWhatIf: 'What-if simulator', dashWhatIfHint: 'Test a resource change without touching your real data.',
    dashSimAddTeacher: '+1 teacher', dashSimRemoveRoom: 'Remove a room', dashSimReset: 'Reset',
    dashSimRun: 'Simulate', dashSimRunning: 'Simulating...', dashSimCurrent: 'Current', dashSimProjected: 'Projected',
    dashSimClashesN: (n) => `${n} clash${n > 1 ? 'es' : ''}`,
    dashNoData: 'Generate a timetable to see statistics.',
    dashDone: 'done',
    dashOver: 'over',
    dashNoConflicts: 'No conflicts',
    dashNoConflictsOk: 'Timetable is consistent.',
    dashNoConflictsFirst: 'Generate the timetable first.',
    dashConflictsCount: (n) => `${n} conflict${n !== 1 ? 's' : ''}`,
    dashConflictsFix: 'View and fix →',
    dashHowItWorksTitle: 'How it works',
    dashHowItWorks1: '1. In the left menu, Data section: add or edit your groups, courses, lecturers and rooms.',
    dashHowItWorks2: '2. Go to Timetable and click Generate — the algorithm places sessions automatically.',
    dashHowItWorks3: '3. Export as PDF and share the file on WhatsApp.',
    dashDemoNote: 'Demo data may be preloaded. Replace it with your own in the Data menu.',

    ttTitle: 'Timetable',
    ttSubtitle: 'Generate the timetable, export as PDF, then share it in your WhatsApp groups.',
    ttGenerate: 'Generate timetable',
    ttGenerating: 'Generating...',
    ttExport: 'Export',
    ttExportPdf: 'PDF (IUGET format)',
    ttExportAllLevels: 'PDF — All levels (1 page/class)',
    ttExportPerLecturer: 'PDF — Per teacher (1 page/teacher)',
    diagTitle: 'Before you generate — things to check',
    diagGroupOverflow: (g, n, cap) => `${g}: ${n} sessions required this week, but only ${cap} time slots available. Reduce courses or add slots.`,
    diagOversizedGroup: (g, size, max) => `${g} (${size} students): no room is large enough (max ${max} seats). Add a bigger room.`,
    diagRoomSupply: (mode, demand, supply) => `${mode} slots: ${demand} sessions to place but only ${supply} room×slots. Room clashes are likely — add a room.`,
    diagLecOverload: (lec, load, cap) => `${lec}: ${load} sessions are forced onto them, but only ${cap} slots available. Add a lecturer for those courses.`,
    ttExportExcel: 'Export to Excel',
    ttPrint: 'Print',
    ttClear: 'Clear',
    ttShareHint: 'PDF downloaded — open WhatsApp and send it to your student groups.',
    ttPrereqTitle: 'Before you generate',
    ttPrereqIntro: 'Automatic generation uses your data. Add it first in the Data menu (left sidebar), then come back here.',
    ttPrereqGroups: 'Groups (classes / programmes)',
    ttPrereqCourses: 'Courses (subjects to schedule)',
    ttPrereqLecturers: 'Lecturers',
    ttPrereqRooms: 'Rooms',
    ttPrereqManage: 'Manage',
    ttPrereqReady: 'All set — you can generate.',
    ttPrereqMissing: (items) => `Missing: ${items}. Click Manage to add them.`,
    ttEmptyTitle: 'No timetable generated yet',
    ttEmptyBody: 'Once you have added groups, courses, lecturers and rooms, click "Generate timetable". The algorithm will build the schedule automatically.',
    ttConfirmRegen: 'This will clear the current timetable and all manual edits. Continue?',
    ttConfirmClear: 'Clear the entire timetable?',
    ttErrNoData: 'Please add at least one course and one group before generating.',
    ttFilter: 'Filter:',
    ttAll: 'All',
    ttAllHint: 'Overview — each card is a different class',
    ttLevel: 'Level',
    ttClassTimetable: 'Class timetable',
    ttPickClass: 'Pick a class above to see its timetable (one subject per slot).',
    ttDay: 'Day',
    ttEvening: 'Evening',
    ttPdfWhatsapp: 'WhatsApp PDF',
    ttSessions: (n) => `${n} sessions`,
    ttNoConflicts: 'No conflicts',
    ttDragHint: 'Drag and drop to move',
    ttGaConsole: 'Algorithm — Console',
    ttInstitution: 'Institution',
    ttSecondary: 'Secondary School',
    ttUniversity: 'University',
    ttEveningClass: 'Evening class',
    ttSchedule: 'Time',
    ttLock: 'Lock',
    ttUnlock: 'Unlock',
    ttDeleteSession: 'Delete this session',
    ttCopySession: 'Duplicate this session',
    ttAddSession: 'Add a session', ttAddGroup: 'Group', ttAddCourse: 'Course', ttAddTeacher: 'Teacher',
    ttAddRoom: 'Room', ttAddDay: 'Day', ttAddSlot: 'Time slot', ttAddPick: '— Pick —',
    ttConfirmDeleteSession: (label) => `Delete the "${label}" session from this week?`,
    ttMarkMissed: 'Mark as missed',
    ttMissedWithMakeup: 'Missed — needs makeup',
    ttMissedNoMakeup: 'Missed — no makeup',
    ttUnmarkMissed: 'Undo absence',
    ttMissedBadge: 'Missed',
    ttMakeupBadge: 'Makeup',
    ttBlock: 'block',
    ttGenerateDisabled: 'Add groups, courses, lecturers and rooms first',
    ttSavedToHistory: 'Saved to History.',
    ttOpenHistory: 'Open History →',
    ttArchiveView: 'Viewing archive',
    ttBackToLive: 'Back to live',
    ttScrollHint: 'Scroll horizontally to see all days',
    ttDays: 'days',
    ttGroupsLegend: 'Each card = one course for one group (e.g. GL-3A, RT-EVENING). Multiple cards in a cell = several groups at the same time.',
    ttSessionLabel: (n, total) => `Session ${n}/${total}`,
    ttSessionWeek: (n, total) => `${n} of ${total} this week`,
    ttGenHowTitle: 'How does generation work?',
    ttGenHowBody: 'The engine reads your Groups, Courses, Lecturers and Rooms (Data menu), then places each session in a free slot for the selected week (Settings → week number). It avoids double bookings (same teacher, room, or group). Regenerate replaces the current week — only one copy is saved to History.',
    thTitle: 'Timetable history',
    thSubtitle: 'Each generation is saved here automatically with week and date.',
    thEmpty: 'No archived timetables',
    thEmptyHint: 'Generate a timetable on the Timetable page — it will appear here immediately.',
    thGenerated: 'Generated',
    thSessions: 'sessions',
    thBy: 'By',
    thView: 'View',
    thRestore: 'Restore',
    thConfirmRestore: 'Replace the current timetable with this version?',
    thConfirmDelete: 'Delete this archive?',
    thNote: 'Past and current timetables are saved in the browser\'s local database (IndexedDB « UniScheduleDB ») — they persist after you close the app. Exported PDFs go to your Downloads folder. Restore replaces the live timetable.',
    mgLegendTitle: 'How to read this grid',
    mgLegendBody: 'Under each day (Monday, Tuesday…), the small columns are your student groups: GL-3A, GL-3B, GL-EVENING, etc. — like IUGET / ENSPD / IAI timetables.',
  },
};

export function t(lang, key, ...args) {
  const pack = UI_STRINGS[lang] || UI_STRINGS.fr;
  const val = pack[key];
  if (typeof val === 'function') return val(...args);
  return val ?? key;
}
